### ISSUE TITLE
Map fitting datatypes to used fields

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/database#1]
|        Field        | Datatype |
|-------------------|----------|
| uri                   | varchar(200)     |
| label               |  varchar(200)        |
| comment             |  text        |
| repository          |  varchar(200)        |
| programmingLibrary  |  extra table       |
| homepage            |   varchar(200)       |
| language            |  extra table    |
| client              | extra datatype          |
| databaseSystem      |  extra datatype        |
| interoperability    |  extra table        |
| programmingLanguage | extra table         |
| operatingSystem     |  extra table        |
| license             |  extra table        |

**Comment by KonradHoeffner** [comment]
labels are text right now but we could switch to varchar. the longest label right now has length 178, so lets use varchar(200).
```
SELECT ?l strlen(?l)
{
 ?x rdfs:label ?l.
}
order by desc(strlen(str(?l)))
```
Edit: Maximum length of uris is 163, so use varchar(200) too.

**Comment by KonradHoeffner** [comment]
comments are changed from text to varchar as well. use length 1000 because that fits all except one, which I will shorten.

```
SELECT ?x ?l strlen(?l)
{
 ?x rdfs:comment ?l.
}
order by desc(strlen(str(?l)))
```

x | l | callret-2
-- | -- | --
http://www.ontodm.com/OntoDM-core/OntoDM_000087 | "Estimating the (Joint) Probability Distribution. A set of data (of type T) is often assumed to be a sample taken from a population according to a probability distribution. A probability distribution/density function assigns a non-negative probability/density to each object of type T. Probably the most general data mining task (Hand et al. 2001) is the task of estimating the (joint) probability distribution D over type T from a set of data items or a sample drawn from that distribution. As mentioned above, in the most typical case we would have T = Tuple(T1, . . ., Tk), where each of T1, . . ., Tk is Boolean, Discrete(S) or Real. We talk about the joint probability distribution to emphasize the difference to the marginal distributions of each of the variables of type T1, . . ., Tk: the joint distribution captures the interactions among the variables. Representing multi-variate distributions is a non-trivial task. Two approaches are commonly used in data mining. In the density-based clustering paradigm, mixtures of multi-variate Gaussian distributions are typically considered (Hand et al. 2001). Probabilistic graphical models, most notably Bayesian networks, represent graphically the (in)dependencies between the variables: Learning their structure and parameters is an important approach to the problem of estimating the joint probability distribution." | 1370

update: the expert says, keep as text, for maximum flexibility.

**Comment by KonradHoeffner** [comment]
libraries get their own table.

**Comment by ThomasPause** [comment]
new tables for library, language, interoperability, programming language, operatingSystem and license to combine values with softwareproducts (Caution!: needs to be filled with data before new softwareproducts can be addes!)

**Comment by ThomasPause** [comment]
modelled everything with an SQL-Script for schema-creation

**Comment by ThomasPause** [comment]
done.
